name: deploy

on:
  workflow_run:
    workflows: [test-deploy]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DEPLOY_DIR
          script_stop: true
          script: |
            cd ${{ env.DEPLOY_DIR }}
            git checkout main
            git pull
            npm ci
            pm2 restart nco-docs