name: test-deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - name: checkout code 
            uses: actions/checkout@v4
          
          - name: install dependencies
            run: npm ci

          - name: build docs
            run: npm run build

            
